### PR TITLE
Fixing id generation on radio buttons. fixes #194

### LINKED ISSUE #194: `radio_button` id attribute is not generated correctly
See: https://github.com/phoenixframework/phoenix_html/blob/v2.10.5/lib/phoenix_html/form.ex#L668

So if radio button value is "purple elephant", id generated will become `record_field_purple elephant`

I think value needs to be stripped of all spaces before concatenating with `input_id/2` .. or replaced with "_"

### PR DESCRIPTION
**Pull request by GBH**
Made a `input_id/3` just so it's easier to generate `for` attribute on labels. Maybe it makes sense to expand `label` to allow value passing. Not sure. One thing at the time.

### CODE REVIEW

File: lib/phoenix_html/form.ex [hunk 1]
```diff
@@ -332,6 +332,10 @@ defmodule Phoenix.HTML.Form do
     do: "#{id}_#{field}"
   def input_id(name, field) when is_atom(name),
     do: "#{name}_#{field}"
+  def input_id(name, field, value) do
```
Comment (josevalim) [inline lib/phoenix_html/form.ex]: I don't think we need to make this function public. What if we call it `radio_button_id` and keep it private for now?

File: lib/phoenix_html/form.ex [hunk 2]
```diff
@@ -332,6 +332,10 @@ defmodule Phoenix.HTML.Form do
...
+    value_id = value |> String.downcase |> String.replace(~r/\W/, "_")
```
Comment (josevalim) [inline lib/phoenix_html/form.ex]: Why do we need to downcase?

Comment (josevalim) [reply lib/phoenix_html/form.ex]: We should probably set the Unicode flag in the regex: `~r/\W/u`.

**Comment by josevalim** [comment]
I have added some comments, thank you @GBH!

File: lib/phoenix_html/form.ex (hunk 1 above)
Comment (GBH) [reply lib/phoenix_html/form.ex]: This is basically so I can do `label(name, field, for: input_id(name, field, value))`. Otherwise I gotta re-implement that again. Also this method is useful for checkbox collection (when you have `name: "search[keys][]` for example) and need unique ids just like for radio buttons.

File: lib/phoenix_html/form.ex (hunk 2 above)
Comment (GBH) [reply lib/phoenix_html/form.ex]: Downcasing is just to make it look consistent. "search_key_foo" looks better than "search_key_FoO". Gotcha on the unicode thing (coming from ruby I didn't know it's a thing)

File: lib/phoenix_html/form.ex (hunk 1 above)
Comment (josevalim) [reply lib/phoenix_html/form.ex]: I see, agreed. If that's the case, we need to add documentation to it, as it is effectively a separate function than `input_id/2`.

File: lib/phoenix_html/form.ex (hunk 2 above)
Comment (josevalim) [reply lib/phoenix_html/form.ex]: Let's remove `downcase` then. It is not necessary. If people want it downcase, then they can pass it explicitly using the input_id/3 function. :D

File: lib/phoenix_html/form.ex (hunk 1 above)
Comment (GBH) [reply lib/phoenix_html/form.ex]: Will do

File: lib/phoenix_html/form.ex (hunk 2 above)
Comment (GBH) [reply lib/phoenix_html/form.ex]: Fair enough. Will update PR for tomorrow.

**Comment by GBH** [comment]
@josevalim PR is amended
